/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/test.glb -o src/components/test.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Jumbo(props) {
  const { nodes, materials } = useGLTF('/models/test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Liqvid.geometry} material={materials['Material.001']} position={[0, 0.209, 0]} scale={[0.483, 1, 0.979]} />
      <mesh geometry={nodes['HH_-_Pack___Label'].geometry} material={materials['HH - Pack _ Label']} position={[0.628, -0.965, 0.001]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[0, 0.378, 0]} scale={[0.106, 0.131, 0.102]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.005']} position={[0.008, -1.039, 0]} scale={[0.613, 1.516, 1.055]} />
      <mesh geometry={nodes.Cap.geometry} material={materials['Material.008']} position={[0, 1.484, 0]} scale={[0.55, 1.411, 1.107]} />
    </group>
  )
}

useGLTF.preload('/models/test.glb')
