/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ocean.glb -o src/components/ocean2.jsx -r public 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/ocean.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh 
        name="Bottle" 
        geometry={nodes.Bottle.geometry} 
        material={materials['Material.001']} 
        scale={[1, 1.239, 1]} />
        <mesh name="Liquid" geometry={nodes.Liquid.geometry} material={materials['Material.002']} scale={[1.01, 1.252, 1.01]} />
        <mesh name="Bottle2" geometry={nodes.Bottle2.geometry} material={materials['cap.001']} scale={[1, 1.239, 1]} />
        <group name="nozzle" position={[0, 2.754, 0]} scale={[0.236, 0.317, 0.236]}>
          <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials['cap.001']} />
          <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials['cap.002']} />
        </group>
        <mesh name="Cap" geometry={nodes.Cap.geometry} material={materials.cap} position={[0, 2.964, 0]} scale={[1, 1.239, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/ocean.glb')
