/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/peach.glb -o src/components/peach.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Peach(props) {
  const { nodes, materials } = useGLTF('/models/peach.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.texture_pbr_v128.geometry} material={materials['Material.001']} position={[2.677, 0.885, -0.408]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/peach.glb')
