/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rose.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from 'framer-motion-3d';
import { useMouseMotionTransform } from '../hooks/useMouseMotionTransform';

export function Rose(props) {
  const { nodes, materials } = useGLTF('/models/rose.glb')
  const { mouse, ...rest } = props;
  const basePosition = [0, 0, 0];
  const baseRotation = [Math.PI / 2, 0, 0];
  const multiplier = 2.4;
  const position = props.position || basePosition;
  const rotation = props.rotation || baseRotation;
  const { positionX, positionY, rotationX, rotationY } = useMouseMotionTransform({
    mouse,
    position,
    rotation,
    multiplier
  });
  return (
    <group {...rest} dispose={null}>
      <motion.mesh
        geometry={nodes.texture_v128_cfg001.geometry}
        material={materials['Material.001']}
        position-x={positionX}
        position-y={positionY}
        position-z={position[2]}
        rotation-x={rotationX}
        rotation-y={rotationY}
        rotation-z={rotation[2]}
      />
    </group>
  )
}

useGLTF.preload('/models/rose.glb')
