/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wood.glb -o src/components/wood.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Wood(props) {
  const { nodes, materials } = useGLTF('/models/wood.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.spate_Material006_0.geometry} material={materials['Material.006']} position={[5.079, -2.288, 0.549]} rotation={[-Math.PI / 2, 0, 0]} scale={5.15} />
    </group>
  )
}

useGLTF.preload('/models/wood.glb')
